version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: postgresql-seiv
      POSTGRES_USER: postgresql_seiv_user
      POSTGRES_PASSWORD: lls7AeXhwxfC4qYJa98wnxNpcveHPBTp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio de API Django
  backend:
    build:
      context: ./  # Busca el Dockerfile dentro de la carpeta 'backend'
      dockerfile: Dockerfile
    restart: always
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app  # Opcional en prod, útil si quieres debuggear sin reconstruir
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Lee las variables del archivo .env que crearemos en la raíz

volumes:
  postgres_data: